# Generated by Django 5.0.1 on 2024-02-10 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pimage', models.ImageField(upload_to='images/')),
                ('pname', models.CharField(max_length=240)),
                ('pdes', models.TextField(null=True)),
                ('ptotal', models.BooleanField(null=True)),
                ('pprice', models.BooleanField(null=True)),
                ('pdiscount', models.CharField(max_length=40)),
                ('photdil', models.IntegerField(null=True)),
                ('psize', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.size')),
            ],
        ),
    ]
