# Generated by Django 5.0.1 on 2024-02-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pprice',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='ptotal',
            field=models.FloatField(null=True),
        ),
    ]
