# Generated by Django 5.0.1 on 2024-02-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_categori_products_pcat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='photdil',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
