# Generated by Django 5.0.1 on 2024-02-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_products_photdil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='product_size1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='product_size2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='product_size3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='product_size4',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
