# Generated by Django 5.0.1 on 2024-02-12 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_size_product_size1_alter_size_product_size2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='psize',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='app.size'),
        ),
    ]
