# Generated by Django 5.0.1 on 2024-03-07 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_address_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
