# Generated by Django 5.0.1 on 2024-03-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.IntegerField(null=True),
        ),
    ]
